#!/bin/bash
ghdjhgdhjhfdj
gvjcfjmgdmhmvjh
nghc zvn cnhdth
hhvgnxnvx nnxbxjvc m
bvnhgcmvnhhchcsg
mnzvgcfvhgnvhcgvc
bnbvbBCfjx,cgmjdnhg
nvmn vjcm bmnb csgm,j
jsvj ,h hgn cbjchsgmchj
jggbfvngvcbhmcnhb
jggbfvngvcbhmcnhb
